---
# PostgreSQL 백업 저장용 PVC (DB 크기의 3-4배 권장)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup-pvc
  namespace: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi  # DB가 10Gi이므로 백업용으로 30Gi 할당
