---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: db
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 31107
      protocol: TCP
  selector:
    app: postgres
