# Bitnami PostgreSQL Helm Chart
# https://github.com/bitnami/charts/tree/main/bitnami/postgresql

auth:
  # Sealed Secret 사용 (db 네임스페이스)
  existingSecret: postgres-helm-secret
  secretKeys:
    adminPasswordKey: postgres-password
    userPasswordKey: password
  username: root
  database: postgres  # 기본 DB

# Primary 설정
primary:
  persistence:
    enabled: true
    size: 5Gi
    storageClass: local-path

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  # Service 설정
  service:
    type: NodePort
    nodePorts:
      postgresql: 31107  # 외부 접근 포트
    ports:
      postgresql: 5432

  # 초기 DB 생성 스크립트
  initdb:
    scripts:
      01-init-databases.sh: |
        #!/bin/bash
        set -e

        echo "Creating application databases..."

        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
          -- Production DB
          CREATE DATABASE movie;
          GRANT ALL PRIVILEGES ON DATABASE movie TO root;

          -- Development DB
          CREATE DATABASE dev_movie;
          GRANT ALL PRIVILEGES ON DATABASE dev_movie TO root;

          \l
        EOSQL

        echo "Databases created successfully!"

# Read Replicas 비활성화
readReplicas:
  replicaCount: 0

# Metrics 비활성화 (필요시 활성화)
metrics:
  enabled: false

# 백업 설정
backup:
  enabled: true
  cronjob:
    # 매일 새벽 2시 백업
    schedule: "0 2 * * *"
    historyLimit: 3
    storage:
      size: 20Gi
      storageClass: local-path
