apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  sources:
    # Helm Chart
    - repoURL: https://charts.bitnami.com/bitnami
      chart: postgresql
      targetRevision: 16.2.1
      helm:
        releaseName: postgres
        valueFiles:
          - $values/values/postgres-values.yaml

    # Values 파일 (GitHub SSH - koalakid1 사용)
    - repoURL: git@github.com:koalakid1/zgoome-infra.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: db

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
