apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: movie-app-production
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/zgoome/movie-frontend.git
    targetRevision: main
    path: .kubernetes/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: movie
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
