apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zgoome-infra
  namespace: argocd
  # Finalizer를 추가하면 Application 삭제 시 모든 리소스도 함께 삭제됨
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: git@github.com:koalakid1/zgoome-infra.git
    targetRevision: main
    path: argocd/applications
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
