---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgC7gyE9dIn4PP3C1bOdHmt7ddq58zA4Q4CpgmnWeg9qWF50gsGjQVUvMRmLzJgK2ff57NtEjeHPP9h06wp3NKJTgCnFADVPnB89m0j2WS/uxMWNUZNPXhVf4tTaea0sWsfjMlfzUYM0UA46JJgfPaAtRGW7i13OeZ8/eXBIq2c3OmkIdFVD6pPsTDD10mw3KPdFk1lQljZWgpiQBEwfca/QyhsNHkTvIqoPKHHjFnXtVLKPAL9y8DF5KSE5jtl7njocnutdmYqU/ADaJGIjEATGCo+pdQvR2RrHhzX8YzZ5FkwWteoTUqgzqyL6kRmK7er07XPA6OmSVwgtrueBhSigRq7P1zbUZ7MKxJ/xEHWPG+VqdLjnBQBe2k8kxw6Hl83rbKOWGWlvU9bHvhsOYNWq/j8Z41vaLTr9LQUghqju44l7F8mHGcqCv1bK9cAY9QYPLHPt5+CXYAvzwMJOcpVGPZ0H7jZwOfuR6o/13E/tKtu3zUy9cPThakO+17TNjk7gaAfRguhzvF1H2BWz1LhcW8T/pwRd/+X83gYMKs3UmZEcUnSh2lDx7Oc0KeMlx1dH+1SyUo32xbl5t8ve7Q/18FtCH+6e6JP3E9C4HvF6Ska4bvirPcAjdfTqvImBjMJ1fx91tVPVJJTFlqeZLMmDHs/fM1MG6eO3d7c4sK8zeoLlO5y3r/4jhXKnE7rXYi1GZeVFRUjGaXg=
    admin-user: AgCKGgCQvvTJJDuslh4QJTWlpCuHDe87auJcCV0rs83rYsVX0/bQ1eLmKYa8rJI+lNVRnCtQC+VBLuhuLDCkO3mydGYDDEoiIPBhHe97FZNg/rMCxIVrVyQ3GLmXoRlbb3qSWrZSrK8Xui9gVBnS7OiusddSUhS12po/81efiPsPT1SygY0Loayc4QkrlU9odj9Upo8fYJ00BOrBebUbzrK8rgOQCMyiLkbmuOFiXmP1gzwj14WhtBND8Xl7GJdEVbA+b1eC5D37KRLqS5y19mxhHPt3J4bUq2AALNqGuUsxg3gd3L32CocLOc898WV9EOXKflAtPSIK6CrRPR3UWO8QToRv2TzWacbynL2IBfrtFd7PqOaB/LYKVNOxB7nJRuQjRDQCSbIQiHY0lN2oJ/6btJDOLrHOXEQ+trwNm8vFT5VtlPiXLFtw4R4P6E9DGpmVgL73yTJOun1EmEfpLkW2tAuYE/b92yaqCFsDhTpfrM+/9FnI7v23DvI1359+MCIbvCDNm3reFs9Atzf1GiHIWnaq+ms2doMiwoHbSoHw4kHoof1SUX/tPkwJbPrJyqzcGE+fpxMm1bTHD6SEVv7A8lhz0rmeYya9O/eV3yKkY6K5J/sFCdG+Rjh9zf3NaObfWdwHFjWc0n49dJDYE5UGa2DQRCWqACWvEMmurXbi5ULFL5WbTM6O4arwj+50WzJAbAjn7g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
