---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: postgres-secret
  namespace: db
spec:
  encryptedData:
    password: AgAOISaLFqxkkNDh3ZheI2JqmMoO2a5UY2JhLaGivTyiJRtiE+i47WDhKY46JKpSU0nlygShIpdRwX56Axw53PQYXBPzj1NuVuDbhog2r+Wtq66QkwId0iUkMQyMQa+YDwpfzeAiwXmDmCdscGe1fR+R6pIJD8PtmH1OTUNWHw7JL4VWtW6d1VyKwx0qjs1zUtxdf2agmhYDi4caj+b/fFyUiTkspbIoaxeXdyhMJ0wc/QlmxZKlWMKkuWnUdDqwuV2kNfzvzvZEjGdcGAc+jod7ttu55GO49I8tOSPxAoxjHsvqZq3YoOKro/oZ9aRjgslNUekkTvDSf0AlYffGv3nqG8Zs5gDVQQnb2TVkBAQ9+B24oykda5J0NIs9ejWgMS9BcNBYfRokJmGF6LkKJhwN3PPetkM9qwWuZA4z2KBwjOEAXFMgtUrm7nEZBYpOnNv2y9cLo0S+MxSpExoSGFVlmIZtA4IL0Y5VMFf2uAgeokul68YN835rEM8c65GWglIcqC9ay4L2VW4SrKOZNPLBrhVjcggR1ydLi9FCpO9rJITfLVCrnwIkssk87slifCV8D8T+x05oRWr0z8ti/bAhpThhVC1TUyigOJlb8RkV/SeKJVtpw5zLMG/9r/Q91mBUmHF2GS/Op7/86LcWuQa50EcB/r4k9pWACOoTVcGVeEKB9ivkDFLyBd5sNWzPCTKfghEzuryqKhA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: postgres-secret
      namespace: db
