apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: common-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Postgres 배포 후
spec:
  project: default

  source:
    repoURL: git@github.com:koalakid1/zgoome-infra.git
    targetRevision: main
    path: argocd/resources/services
    directory:
      recurse: false

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
