apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Secret 먼저 배포
spec:
  project: default

  source:
    repoURL: git@github.com:koalakid1/zgoome-infra.git
    targetRevision: main
    path: argocd/resources/secrets
    directory:
      recurse: false  # 하위 폴더는 검색 안 함

  destination:
    server: https://kubernetes.default.svc
    # namespace 지정 안 함 - 각 SealedSecret의 metadata.namespace 사용

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
